program {name}TestProject;
{

  DUnit Test Project generated by dtest

}

{$IFDEF CONSOLE_TESTRUNNER}
{$APPTYPE CONSOLE}
{$ENDIF}

uses
  Forms,
  TestFramework,
  GUITestRunner,
  TextTestRunner,
  XMLTestRunner,
  {name}TestSuite in '{name}TestSuite.pas';

begin
  Application.Initialize;
  if(Pos('--xml', ParamStr(1)) > 0) then
    XMLTestRunner.RunRegisteredTests
  else if IsConsole then
    TextTestRunner.RunRegisteredTests
  else
    GUITestRunner.RunRegisteredTests;
end.